services:

  packages:
    build:
      context: ./vaka-js
      dockerfile: Dockerfile
    entrypoint:
      - sh
      - -c
      - |
        yarn workspace @vakaconsulting/common run watch & \
        yarn workspace @vakaconsulting/react run watch & \
        yarn workspace @vakaconsulting/web3-auth run watch 
    volumes:
      - ./vaka-js/packages:/app/packages

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9001:9001"
    volumes:
      - ./api/src:/app/api/src:ro
    depends_on:
      - db

  app:
    build:      
      context: app
      dockerfile: Dockerfile
    
    volumes:
      - ./app/components:/app/components:ro
      - ./app/constants:/app/constants:ro
      - ./app/contexts:/app/contexts:ro
      - ./app/hooks:/app/hooks:ro
      - ./app/lib:/app/lib:ro
      - ./app/pages:/app/pages:ro
      - ./app/providers:/app/providers:ro
      - ./app/public:/app/public:ro
      - ./app/styles:/app/styles:ro      
      - ./app/types:/app/types:ro
      - ./app/postcss.config.mjs:/app/postcss.config.mjs:ro
      - ./app/eslint.config.mjs:/app/eslint.config.mjs:ro
      - ./app/next.config.ts:/app/next.config.ts:ro
      - ./app/components.json:/app/components.json:ro
      - ./app/tsconfig.json:/app/tsconfig.json:ro
      - ./app/tsconfig.json:/app/tsconfig.json:ro
      - ./app/package.json:/app/package.json:ro
      - ./vaka-js/packages/common/dist:/app/node_modules/@vakaconsulting/common/dist:ro
      - ./vaka-js/packages/config/dist:/app/node_modules/@vakaconsulting/config/dist:ro
      - ./vaka-js/packages/react/dist:/app/node_modules/@vakaconsulting/react/dist:ro
      - ./vaka-js/packages/web3-auth/dist:/app/node_modules/@vakaconsulting/web3-auth/dist:ro
    
    ports:
      - "3001:3000"
    
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_WEB3_AUTH_ENDPOINT=http://localhost:9001/
    
    env_file:
      - .env
    
    command:
      - 'npm run dev'
    # command: 
    #   - 'npm install && sleep 500000'
    
    depends_on:
      - api

  db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: